Support priorityClassName in Helm chart
liqotech/liqo pull request #2345
Opened 2024-02-21 08:59 UTC by EladDolev

# Description

This PR adds support for defining [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) on some of the pods

It is especially useful for the `liqo-route` as in real case scenarios it is not being schedule to some of the worker nodes and it breaks the network for anything which is running there. When assigning a high (enough) priority to `liqo-route` it is always scheduled to all of the worker nodes

# How Has This Been Tested?

- [x] Test A
Installed with default values -> no priorityClassName exists on any of the pods
- [x] Test B
Assigned priorityClassName values to all relevant workloads and the workloads are running with priorityClassName

2024-02-27 09:37 UTC, fra98 commented
Hi @EladDolev, thanks for your contribution. It seems like a useful feature.

Btw, keep in mind that the `liqo-route` daemonset is going to be replaced in the next release, due to a major refactoring of the liqo networking.

2024-02-27 09:40 UTC, fra98 requested changes
Can you also add the `PriorityClass` value to the `crdReplicator`, `discovery`, and `metric-agent` pods?
Also, you can correctly generate the README.md file with the command `make docs`.

2024-02-29 15:36 UTC, EladDolev commented
Done as requested @fra98 
Much appreciated 🙏

2024-02-29 15:44 UTC, fra98 approved these changes

2024-02-29 15:47 UTC, fra98 commented
LGTM!
Can you please rebase to the latest commit on master and squash the commits into one? Then we are ready to merge

2024-02-29 17:40 UTC, EladDolev commented
Done @fra98 
Thanks !!

2024-03-01 08:06 UTC, fra98 commented
/rebase test=true

2024-03-01 09:30 UTC, fra98 commented
/test

2024-03-01 09:48 UTC, fra98 commented
/merge

2024-03-01 09:48 UTC, merged