Liqo installer improvement for Liqo Agent installation
liqotech/liqo pull request #341
Opened 2020-10-20 10:39 UTC by AbakusW

# Description

This PR adds a section to the Liqo installer to let users install and uninstall the latest version of the Liqo Agent as a desktop application.

- **[ADDED]** files to make the Agent binary as a desktop application
  - xdg *.desktop* file
  - *.svg* scalable logo

- **[ADDED]** new iconset for the desktop banner notifications

2020-10-20 17:08 UTC, giorio94 requested changes
First, thanks @AbakusW for having split down this PR. Much easier to read and review now.

I left some comments inline. Most simply relate to style and should be very easy to address. 
At the core, to me, the `get_liqo_agent` function should be improved, especially for what regards getting the correct release instead of using always the latest one.

Additionally, the `get_agent_link` and `setup_agent_environment` should be good candidates for a couple of unit tests if you want to try implementing them.

Finally, I feel a bit odd having icon files inside the `scripts` directory. Shouldn't them be in an appropriate directory?

As always, feel free to ask if something is not clear or a comment seems wrong. Definitely possible.

2020-10-21 17:24 UTC, AbakusW commented on install.sh
> +	AGENT_XDG_CONFIG_DIR="${HOME}/.config/"
thanks for this!

2020-10-21 17:27 UTC, AbakusW commented on install.sh
> +	if [[ $# -ge 1 ]] && [[ "$1" == "-c" ]]; then
As for similar changes, thank you for having me discover this quick fallback bash syntax I never heard of

2020-10-28 08:06 UTC, giorio94 reviewed
Thanks @AbakusW for all the improvements.

Just a couple of additional suggestions. Very easy to address (most are just stylistic), but some are definitely necessary as the installer currently fails to install the agent (at least when I tried). Please, after fixing them, double check that the installation process completes correctly.

A second problem is that the installation of the v0.1 is broken, as the layout of the repo changed (it fails to retrieve the icons). My suggestion there is to manually delete the binary from that release (which I nonetheless suppose not being yet fully functional), and do a follow-up release when everything will be ready. @palexster WDYT?

2020-10-28 08:09 UTC, palexster commented
> A second problem is that the installation of the v0.1 is broken, as the layout of the repo changed (it fails to retrieve the icons). My suggestion there is to manually delete the binary from that release (which I nonetheless suppose not being yet fully functional), and do a follow-up release when everything will be ready. @palexster WDYT?

Ok to me. We will publish the agent for the v0.2 or make a v0.1.1 with the agent correctly generated.

2020-10-28 12:16 UTC, AbakusW commented
> 
> 
> > A second problem is that the installation of the v0.1 is broken, as the layout of the repo changed (it fails to retrieve the icons). My suggestion there is to manually delete the binary from that release (which I nonetheless suppose not being yet fully functional), and do a follow-up release when everything will be ready. @palexster WDYT?
> 
> Ok to me. We will publish the agent for the v0.2 or make a v0.1.1 with the agent correctly generated.

@palexster seems good to me too, this way we can also have the opportunity to merge #214 and #351 first, thus having a fully functioning version with a couple of working features

2020-10-29 12:14 UTC, palexster approved these changes

2020-10-29 14:15 UTC, giorio94 approved these changes
/lgtm

Two minor things I noticed just now, the icon and the desktop file should probably be moved to the assets directory, to leave only proper scripts in the scripts directory

2020-10-29 17:26 UTC, merged